<?php

    namespace Database\Seeders;

    use App\Libraries\AppLibrary;
    use Illuminate\Database\Seeder;
    use Spatie\Permission\Models\Permission;

    class PermissionTableSeeder extends Seeder
    {
        public function run() : void
        {
            $permissions = [
                [
                    'title'      => 'Dashboard' ,
                    'name'       => 'dashboard' ,
                    'guard_name' => 'web' ,
                    'url'        => 'dashboard' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Product Attributes' ,
                    'name'       => 'product_attributes' ,
                    'guard_name' => 'web' ,
                    'url'        => 'product/product-attributes' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Product Attributes Create' ,
                            'name'       => 'product_attributes_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'product_attributes/create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Product Attributes Edit' ,
                            'name'       => 'product_attributes_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'product_attributes/edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Product Attributes Delete' ,
                            'name'       => 'product_attributes_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'product_attributes/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Product Attributes Show' ,
                            'name'       => 'product_attributes_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'product_attributes/show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Product Categories' ,
                    'name'       => 'product_categories' ,
                    'guard_name' => 'web' ,
                    'url'        => 'product/product-categories' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Product Categories Create' ,
                            'name'       => 'product_categories_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'product-categories/create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Product Categories Edit' ,
                            'name'       => 'product_categories_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'product-categories/edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Product Categories Delete' ,
                            'name'       => 'product_categories_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'product-categories/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Product Categories Show' ,
                            'name'       => 'product_categories_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'product-categories/show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Raw materials' ,
                    'name'       => 'ingredients' ,
                    'guard_name' => 'web' ,
                    'url'        => 'ingredients' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Raw materials Create' ,
                            'name'       => 'ingredients_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'ingredients/create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Raw materials Edit' ,
                            'name'       => 'ingredients_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'ingredients/edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Raw materials Delete' ,
                            'name'       => 'ingredients_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'ingredients/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Raw materials Show' ,
                            'name'       => 'ingredients_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'ingredients/show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Payment Accounts' ,
                    'name'       => 'payment_accounts' ,
                    'guard_name' => 'web' ,
                    'url'        => 'accounting/payment_accounts' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Payment Accounts Create' ,
                            'name'       => 'payment_accounts_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Payment Accounts Edit' ,
                            'name'       => 'payment_accounts_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Payment Accounts Delete' ,
                            'name'       => 'payment_accounts_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Payment Accounts Show' ,
                            'name'       => 'payment_accounts_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Chart of Accounts' ,
                    'name'       => 'chart_of_accounts' ,
                    'guard_name' => 'web' ,
                    'url'        => 'accounting/chart_of_accounts' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Chart of Accounts Create' ,
                            'name'       => 'chart_of_accounts_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Chart of Accounts Edit' ,
                            'name'       => 'chart_of_accounts_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Chart of Accounts Delete' ,
                            'name'       => 'chart_of_accounts_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Chart of Accounts Show' ,
                            'name'       => 'chart_of_accounts_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Journal Entries' ,
                    'name'       => 'journal_entries' ,
                    'guard_name' => 'web' ,
                    'url'        => 'accounting/journal_entries' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Journal Entries Create' ,
                            'name'       => 'journal_entries_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Journal Entries Edit' ,
                            'name'       => 'journal_entries_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Journal Entries Delete' ,
                            'name'       => 'journal_entries_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Journal Entries Show' ,
                            'name'       => 'journal_entries_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Stock Transfers' ,
                    'name'       => 'stock_transfers' ,
                    'guard_name' => 'web' ,
                    'url'        => 'stock_transfers' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Stock Transfers Create' ,
                            'name'       => 'stock_transfers_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Stock Transfers Edit' ,
                            'name'       => 'stock_transfers_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,

                        [
                            'title'      => 'Stock Transfers Show' ,
                            'name'       => 'stock_transfers_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Stock Requests' ,
                    'name'       => 'stock_requests' ,
                    'guard_name' => 'web' ,
                    'url'        => 'stock_requests' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Stock Requests Create' ,
                            'name'       => 'stock_requests_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Stock Requests Edit' ,
                            'name'       => 'stock_requests_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,

                        [
                            'title'      => 'Stock Requests Show' ,
                            'name'       => 'stock_requests_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Ingredients' ,
                    'name'       => 'ingredients' ,
                    'guard_name' => 'web' ,
                    'url'        => 'ingredients' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Raw materials Create' ,
                            'name'       => 'ingredients_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'ingredients/create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Raw materials Edit' ,
                            'name'       => 'ingredients_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'ingredients/edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Raw materials Delete' ,
                            'name'       => 'ingredients_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'ingredients/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Raw materials Show' ,
                            'name'       => 'ingredients_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'ingredients/show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Products' ,
                    'name'       => 'products' ,
                    'guard_name' => 'web' ,
                    'url'        => 'products' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Products Create' ,
                            'name'       => 'products_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'products/create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Products Edit' ,
                            'name'       => 'products_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'products/edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Products Delete' ,
                            'name'       => 'products_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'products/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Products Show' ,
                            'name'       => 'products_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'products/show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Production Planning' ,
                    'name'       => 'production_planning' ,
                    'guard_name' => 'web' ,
                    'url'        => 'production/setup' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Production Planning Create' ,
                            'name'       => 'planning_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'production/setup' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Production Planning Edit' ,
                            'name'       => 'planning_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'production/setup' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Production Planning Delete' ,
                            'name'       => 'planning_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'production/setup' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Production Manufacturing' ,
                    'name'       => 'production_manufacturing' ,
                    'guard_name' => 'web' ,
                    'url'        => 'production/production' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Manufacturing Create' ,
                            'name'       => 'production_manufacturing_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'production/production' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Manufacturing Edit' ,
                            'name'       => 'production_manufacturing_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'production/production' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Manufacturing Delete' ,
                            'name'       => 'production_manufacturing_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'production/production' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Production Outputs' ,
                    'name'       => 'production' ,
                    'guard_name' => 'web' ,
                    'url'        => 'production/output' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Create' ,
                            'name'       => 'production_output_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'production/output' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Edit' ,
                            'name'       => 'production_output_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'production/output' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Delete' ,
                            'name'       => 'production_output_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'production/output' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Product Stocking' ,
                    'name'       => 'purchase' ,
                    'guard_name' => 'web' ,
                    'url'        => 'purchase' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Stocking Create' ,
                            'name'       => 'purchase_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'purchase/create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Stocking Edit' ,
                            'name'       => 'purchase_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'purchase/edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Stocking Delete' ,
                            'name'       => 'purchase_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'purchase/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Stocking Show' ,
                            'name'       => 'purchase_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'purchase/show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Administrators' ,
                    'name'       => 'administrators' ,
                    'guard_name' => 'web' ,
                    'url'        => 'administrators' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Administrators Create' ,
                            'name'       => 'administrators_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'administrators/create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Administrators Edit' ,
                            'name'       => 'administrators_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'administrators/edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Administrators Delete' ,
                            'name'       => 'administrators_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'administrators/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Administrators Show' ,
                            'name'       => 'administrators_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'administrators/show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Customers' ,
                    'name'       => 'customers' ,
                    'guard_name' => 'web' ,
                    'url'        => 'customers' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Customers Create' ,
                            'name'       => 'customers_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'customers/create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Customers Edit' ,
                            'name'       => 'customers_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'customers/edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Customers Delete' ,
                            'name'       => 'customers_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'customers/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Customers Show' ,
                            'name'       => 'customers_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'customers/show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Warehouses' ,
                    'name'       => 'warehouses' ,
                    'guard_name' => 'web' ,
                    'url'        => 'warehouses' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Warehouse Create' ,
                            'name'       => 'warehouses_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'warehouses/create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Warehouse Edit' ,
                            'name'       => 'warehouses_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'warehouses/edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Warehouse Delete' ,
                            'name'       => 'warehouses_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'warehouses/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Warehouse Show' ,
                            'name'       => 'warehouses_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'warehouses/show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Quotations' ,
                    'name'       => 'quotation' ,
                    'guard_name' => 'web' ,
                    'url'        => 'quotation' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Quotations Create' ,
                            'name'       => 'quotation_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'quotation/create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Quotations Edit' ,
                            'name'       => 'quotation_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'quotation/edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Quotations Delete' ,
                            'name'       => 'quotation_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'quotation/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Quotations Show' ,
                            'name'       => 'quotation_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'quotation/show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Employees' ,
                    'name'       => 'employees' ,
                    'guard_name' => 'web' ,
                    'url'        => 'employees' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Employees Create' ,
                            'name'       => 'employees_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'employees/create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Employees Edit' ,
                            'name'       => 'employees_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'employees/edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Employees Delete' ,
                            'name'       => 'employees_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'employees/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Employees Show' ,
                            'name'       => 'employees_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'employees/show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Damages' ,
                    'name'       => 'damages' ,
                    'guard_name' => 'web' ,
                    'url'        => 'damages' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Damage Create' ,
                            'name'       => 'damage_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'damages/create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Damage Edit' ,
                            'name'       => 'damage_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'damages/edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Damage Delete' ,
                            'name'       => 'damage_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'damages/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Damage Show' ,
                            'name'       => 'damage_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'damages/show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Truck Stock' ,
                    'name'       => 'truck_Stock' ,
                    'guard_name' => 'web' ,
                    'url'        => 'distribution-routes/truck-stock' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Commission Summary' ,
                    'name'       => 'commission_summary' ,
                    'guard_name' => 'web' ,
                    'url'        => 'distribution-routes/commission-summary' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Commission Payout' ,
                    'name'       => 'commission_payout' ,
                    'guard_name' => 'web' ,
                    'url'        => 'distribution-routes/commission-payout' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Commission Payout Create' ,
                            'name'       => 'commission_payout_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'damages/create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,

                        [
                            'title'      => 'Commission Payout Delete' ,
                            'name'       => 'commission_payout_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'damages/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                    ]
                ] ,
                [
                    'title'      => 'Distribution Hub' ,
                    'name'       => 'distribution_hub' ,
                    'guard_name' => 'web' ,
                    'url'        => 'distribution-routes' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Distribution Route Create' ,
                            'name'       => 'distribution_hub_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'damages/create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Distribution Route Edit' ,
                            'name'       => 'distribution_hub_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'damages/edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Distribution Route Delete' ,
                            'name'       => 'distribution_hub_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'damages/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Distribution Route Show' ,
                            'name'       => 'distribution_hub_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'distribution-routes/show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Commission Rules' ,
                    'name'       => 'commission' ,
                    'guard_name' => 'web' ,
                    'url'        => 'distribution-routes/commission' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Commission Rules Create' ,
                            'name'       => 'commission_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Commission Rules Edit' ,
                            'name'       => 'commission_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Commission Rules Delete' ,
                            'name'       => 'commission_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'damages/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Commission Rules Show' ,
                            'name'       => 'commission_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'distribution-routes/show' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Activity Logs' ,
                    'name'       => 'activity_logs' ,
                    'guard_name' => 'web' ,
                    'url'        => 'activity_logs' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'POS Orders Edit' ,
                    'name'       => 'pos_orders_edit' ,
                    'guard_name' => 'web' ,
                    'url'        => 'dining-table/edit' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Product Settings' ,
                    'name'       => 'product_settings' ,
                    'guard_name' => 'web' ,
                    'url'        => 'product' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Stock' ,
                    'name'       => 'stock' ,
                    'guard_name' => 'web' ,
                    'url'        => 'stock' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Stock Reconciliation' ,
                    'name'       => 'stock_reconciliation' ,
                    'guard_name' => 'web' ,
                    'url'        => 'stock_reconciliation' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Suppliers' ,
                    'name'       => 'suppliers' ,
                    'guard_name' => 'web' ,
                    'url'        => 'suppliers' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Raw Materials Purchases' ,
                    'name'       => 'raw_material_purchase' ,
                    'guard_name' => 'web' ,
                    'url'        => 'raw_material_purchase' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Purchase Returns' ,
                    'name'       => 'purchase_returns' ,
                    'guard_name' => 'web' ,
                    'url'        => 'purchase_returns' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Production Report' ,
                    'name'       => 'production_report' ,
                    'guard_name' => 'web' ,
                    'url'        => 'production-report' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Stock Purchases' ,
                    'name'       => 'stock_purchase' ,
                    'guard_name' => 'web' ,
                    'url'        => 'purchase' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Raw Materials' ,
                    'name'       => 'raw_materials' ,
                    'guard_name' => 'web' ,
                    'url'        => 'ingredients_and_stock' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Subscriptions' ,
                    'name'       => 'subscriptions' ,
                    'guard_name' => 'web' ,
                    'url'        => 'subscriptions' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,

                [
                    'title'      => 'Expense Category' ,
                    'name'       => 'expense_category' ,
                    'guard_name' => 'web' ,
                    'url'        => 'categories' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Expense Category Create' ,
                            'name'       => 'categories_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Expense Category Edit' ,
                            'name'       => 'categories_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Expense Category Delete' ,
                            'name'       => 'categories_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Expense Category Show' ,
                            'name'       => 'categories_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'categories' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'Expense' ,
                    'name'       => 'expenses' ,
                    'guard_name' => 'web' ,
                    'url'        => 'expenses' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                    'children'   => [
                        [
                            'title'      => 'Expense Create' ,
                            'name'       => 'expenses_create' ,
                            'guard_name' => 'web' ,
                            'url'        => 'create' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Expense Edit' ,
                            'name'       => 'expenses_edit' ,
                            'guard_name' => 'web' ,
                            'url'        => 'edit' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Expense Delete' ,
                            'name'       => 'expenses_delete' ,
                            'guard_name' => 'web' ,
                            'url'        => 'damages/delete' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ] ,
                        [
                            'title'      => 'Expense Show' ,
                            'name'       => 'expenses_show' ,
                            'guard_name' => 'web' ,
                            'url'        => 'expenses' ,
                            'created_at' => now() ,
                            'updated_at' => now() ,
                        ]
                    ]
                ] ,
                [
                    'title'      => 'POS' ,
                    'name'       => 'pos' ,
                    'guard_name' => 'web' ,
                    'url'        => 'pos' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Add Sale' ,
                    'name'       => 'add_sale' ,
                    'guard_name' => 'web' ,
                    'url'        => 'sales/add' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'POS Orders' ,
                    'name'       => 'pos-orders' ,
                    'guard_name' => 'web' ,
                    'url'        => 'pos-orders' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'POS Credit Orders' ,
                    'name'       => 'pos-credit-orders' ,
                    'guard_name' => 'web' ,
                    'url'        => 'pos-orders/credit' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'POS Deposit Orders' ,
                    'name'       => 'pos-deposit-orders' ,
                    'guard_name' => 'web' ,
                    'url'        => 'pos-orders/deposit' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,

                [
                    'title'      => 'Sales Report' ,
                    'name'       => 'sales-report' ,
                    'guard_name' => 'web' ,
                    'url'        => 'sales-report' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Stock Expiry Report' ,
                    'name'       => 'stock_expiry_report' ,
                    'guard_name' => 'web' ,
                    'url'        => 'stock-expiry-report' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Products Report' ,
                    'name'       => 'products-report' ,
                    'guard_name' => 'web' ,
                    'url'        => 'products-report' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Credit Balance Report' ,
                    'name'       => 'credit-balance-report' ,
                    'guard_name' => 'web' ,
                    'url'        => 'credit-balance-report' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
                [
                    'title'      => 'Settings' ,
                    'name'       => 'settings' ,
                    'guard_name' => 'web' ,
                    'url'        => 'settings' ,
                    'created_at' => now() ,
                    'updated_at' => now() ,
                ] ,
            ];

            $permissions = AppLibrary::associativeToNumericArrayBuilder($permissions);
            Permission::insert($permissions);
        }
    }
