<?php

    use App\Http\Controllers\ActivityLogController;
    use App\Http\Controllers\Admin\AdministratorAddressController;
    use App\Http\Controllers\Admin\AdministratorController;
    use App\Http\Controllers\Admin\BarcodeController;
    use App\Http\Controllers\Admin\BranchController;
    use App\Http\Controllers\Admin\CityController;
    use App\Http\Controllers\Admin\CompanyController;
    use App\Http\Controllers\Admin\CountryCodeController;
    use App\Http\Controllers\Admin\CountryController;
    use App\Http\Controllers\Admin\CurrencyController;
    use App\Http\Controllers\Admin\CustomerAddressController;
    use App\Http\Controllers\Admin\CustomerController;
    use App\Http\Controllers\Admin\DamageController;
    use App\Http\Controllers\Admin\DashboardController;
    use App\Http\Controllers\Admin\EmployeeAddressController;
    use App\Http\Controllers\Admin\EmployeeController;
    use App\Http\Controllers\Admin\IngredientsController;
    use App\Http\Controllers\Admin\LanguageController;
    use App\Http\Controllers\Admin\MailController;
    use App\Http\Controllers\Admin\MenuSectionController;
    use App\Http\Controllers\Admin\MenuTemplateController;
    use App\Http\Controllers\Admin\MyOrderDetailsController;
    use App\Http\Controllers\Admin\NotificationAlertController;
    use App\Http\Controllers\Admin\NotificationController;
    use App\Http\Controllers\Admin\OtpController;
    use App\Http\Controllers\Admin\PaymentGatewayController;
    use App\Http\Controllers\Admin\PermissionController;
    use App\Http\Controllers\Admin\PosController;
    use App\Http\Controllers\Admin\PosOrderController;
    use App\Http\Controllers\Admin\ProductAttributeController;
    use App\Http\Controllers\Admin\ProductAttributeOptionController;
    use App\Http\Controllers\Admin\ProductBrandController;
    use App\Http\Controllers\Admin\ProductCategoryController;
    use App\Http\Controllers\Admin\ProductController;
    use App\Http\Controllers\Admin\ProductsReportController;
    use App\Http\Controllers\Admin\ProductVariationController;
    use App\Http\Controllers\Admin\PurchaseController;
    use App\Http\Controllers\Admin\RoleController;
    use App\Http\Controllers\Admin\SalesReportController;
    use App\Http\Controllers\Admin\SimpleUserController;
    use App\Http\Controllers\Admin\SiteController;
    use App\Http\Controllers\Admin\SmsGatewayController;
    use App\Http\Controllers\Admin\StateController;
    use App\Http\Controllers\Admin\StockController;
    use App\Http\Controllers\Admin\SupplierController;
    use App\Http\Controllers\Admin\TaxController;
    use App\Http\Controllers\Admin\ThemeController;
    use App\Http\Controllers\Admin\TimezoneController;
    use App\Http\Controllers\Admin\UnitController;
    use App\Http\Controllers\API\DistributionRouteController;
    use App\Http\Controllers\Auth\ForgotPasswordController;
    use App\Http\Controllers\Auth\LoginController;
    use App\Http\Controllers\Auth\RefreshTokenController;
    use App\Http\Controllers\ChartOfAccountGroupController;
    use App\Http\Controllers\CleaningOrderController;
    use App\Http\Controllers\CleaningServiceCategoryController;
    use App\Http\Controllers\CleaningServiceController;
    use App\Http\Controllers\CleaningServiceCustomerController;
    use App\Http\Controllers\CommissionController;
    use App\Http\Controllers\CommissionPayoutController;
    use App\Http\Controllers\CreditDepositPurchaseController;
    use App\Http\Controllers\CustomerPaymentController;
    use App\Http\Controllers\ExpenseCategoryController;
    use App\Http\Controllers\ExpensePaymentController;
    use App\Http\Controllers\ExpensesController;
    use App\Http\Controllers\Frontend\LanguageController as FrontendLanguageController;
    use App\Http\Controllers\Frontend\ProfileController;
    use App\Http\Controllers\Frontend\SettingController as FrontendSettingController;
    use App\Http\Controllers\IotecController;
    use App\Http\Controllers\LedgerController;
    use App\Http\Controllers\ModuleController;
    use App\Http\Controllers\PaymentAccountController;
    use App\Http\Controllers\PaymentController;
    use App\Http\Controllers\PaymentMethodController;
    use App\Http\Controllers\PrinterController;
    use App\Http\Controllers\ProductionController;
    use App\Http\Controllers\ProductionProcessController;
    use App\Http\Controllers\ProductionSetupController;
    use App\Http\Controllers\PurchaseReturnController;
    use App\Http\Controllers\StockTransferController;
    use App\Http\Controllers\SubscriptionController;
    use App\Http\Controllers\UnitConversionController;
    use App\Http\Controllers\WarehouseController;
    use App\Http\Controllers\WhatsAppController;
    use App\Http\Resources\ChartOfAccountGroupResource;
    use App\Models\ChartOfAccountGroup;
    use Illuminate\Http\Request;
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Support\Facades\Route;

    Route::post( 'success' , [ IotecController::class , 'success' ] );
    Route::post( 'pay' , [ IotecController::class , 'pay' ] );

    Route::get( 'whatsapp' , [ WhatsAppController::class , 'index' ] )->name( 'whats-app.index' );
    Route::post( 'whatsapp' , [ WhatsAppController::class , 'message' ] )->name( 'whats-app.message' );

    Route::apiResource( 'subscriptions' , SubscriptionController::class );
    Route::get( 'subscriptionPlans' , [ SubscriptionController::class , 'subscriptionPlans' ] );

    Route::prefix( 'frontend' )->name( 'frontend.' )->group( function () {
        Route::prefix( 'setting' )->name( 'setting.' )->group( function () {
            Route::get( '/' , [ FrontendSettingController::class , 'index' ] );
        } );

        Route::prefix( 'language' )->name( 'language.' )->group( function () {
            Route::get( '/' , [ FrontendLanguageController::class , 'index' ] );
            Route::get( '/show/{language}' , [ FrontendLanguageController::class , 'show' ] );
        } );
    } );
