FROM nginx:stable-alpine

# Remove default configs
RUN rm -f /etc/nginx/conf.d/*

# Copy your local config as the default
COPY docker/nginx/conf.d/local/api.local.conf /etc/nginx/conf.d/default.conf

# Copy public folder so Nginx can serve assets directly
COPY public /app/public

WORKDIR /app